#!/usr/bin/env ruby
require 'webkit'
require 'yaml'

wv = Gtk::WebKit::WebView.new
win = Gtk::Window.new
win.add(wv)
win.signal_connect("key-press-event") do |w,e|
  Gtk.main_quit if Gdk::Keyval.to_name(e.keyval) == "q"
  #wv.reload if Gdk::Keyval.to_name(e.keyval) == "r"
end
win.signal_connect("destroy") { Gtk.main_quit }
wv.open "http://localhost:4567/index"
#wv.open "http://localhost:4567/test"
win.show_all
Gtk.main
