#!/bin/env ruby
require 'fileutils'

Dir["#{ENV['HOME']}/images/art/images/**/*.{MOV,THM,mp4}"].each do |movie|
  dest = movie.sub(/images\/art\/images/,"videos")
  FileUtils.mkpath File.dirname(dest)
  FileUtils.mv movie, dest
end
