#!/usr/bin/env ruby
require 'yaml'
require 'mini_exiftool'
require File.join ENV['HOME'],"src/fim","config.rb"

exit unless ARGV.size == 2
@index[ARGV[1]] = []
@index[ARGV[0]].each do |i|
  exif = MiniExiftool.new(i)
  keywords = exif.keywords.to_a
  keywords.delete ARGV[0]
  keywords << ARGV[1]
  keywords.uniq!
  if keywords.size == 1
    exif.keywords = keywords.first
  else
    exif.keywords = keywords
  end
  exif.save
  @index[ARGV[1]] << i
end
File.open(@indexfile,"w+"){|f| f.puts @index.to_yaml}
File.open(@tagfile,"w+"){|f| f.puts ARGV[1].to_s} if ARGV[0] == File.read(@tagfile).chomp
