#!/usr/bin/env ruby
require 'securerandom'
require_relative 'index.rb'

@options = Parser.new do |p|
  p.banner = "fast image manager"
  p.version = ""
  p.option :tag, "select tag(s)", :default => @tag
end.process!

@tag = @options[:tag]

@win.show_all
Gtk.main
