#!/usr/bin/env ruby
require 'yaml'
require 'gtk2'
require_relative "gui.rb"

ARGV[0] ?  file = ARGV[0] : file = @index[@tag][@current]

@image = Gtk::Image.new file

def draw file=@index[@tag][@current]
  pixbuf = Gdk::Pixbuf.new file
  ratio = [@win.screen.width/pixbuf.width.to_f, @win.screen.height.to_f/pixbuf.height].min
  pixbuf = pixbuf.scale(pixbuf.width*ratio, pixbuf.height*ratio)
  @image.pixbuf = pixbuf
end

@win.add(@image)
draw file
@win.show_all
Gtk.main
