#!/usr/bin/env ruby
require 'yaml'
require 'mini_exiftool'
require_relative "fim.rb"

exit unless ARGV.size == 2
@index[ARGV[1].to_s] = []
puts @index.to_yaml
@index[ARGV[0].to_s].each do |i|
  exif = MiniExiftool.new(i)
  begin
    keywords = exif.keywords.to_a
  rescue
    keywords = [exif.keywords]
  end
  keywords.delete ARGV[0]
  keywords << ARGV[1]
  keywords.uniq!
  if keywords.size == 1
    exif.keywords = keywords.first
  else
    exif.keywords = keywords
  end
  exif.save
  @index[ARGV[1].to_s] << i
end
File.open(@indexfile,"w+"){|f| f.puts @index.to_yaml}
File.open(@tagfile,"w+"){|f| f.puts ARGV[1].to_s} if ARGV[0].to_s == File.read(@tagfile).chomp
