#!/bin/sh

/usr/bin/rsync -avi /media/s90/DCIM/ /home/ch/images/art/images/s90/ 
/home/ch/src/fim/fim-mv-videos
/home/ch/src/fim/fim-update-index
/home/ch/src/fim/fim-update-thumbs
echo -n "*" > /home/ch/images/tag
/home/ch/src/fim/fim-index 
