#!/usr/bin/env ruby
require 'yaml'
require 'mini_exiftool'
require File.join ENV['HOME'],"src/fim","config.rb"

@index[ARGV[0]].each do |i|
  exif = MiniExiftool.new(i)
  keywords = exif.keywords.to_a
  keywords.delete ARGV[0]
  keywords.uniq!
  if keywords.empty?
    exif.keywords = nil
  elsif keywords.size == 1
    exif.keywords = keywords.first
  else
    exif.keywords = keywords
  end
  exif.save
end
@index.delete ARGV[0]
File.open(@indexfile,"w+"){|f| f.puts @index.to_yaml}
