#!/usr/bin/env ruby
require_relative "fim.rb"
YAML.load_file(@indexfile).values.flatten.uniq.each do |file|
  thumbnail = file.sub(/#{@imagedir}/,@thumbdir).sub(/jpg/i,'png')
  `/home/ch/src/fim/fim-thumb "#{file}"` unless File.exists? thumbnail
end
