#!/usr/bin/env ruby
require 'yaml'
require 'gtk2'
require File.join ENV['HOME'],"src/fim","config.rb"

win = Gtk::Window.new
win.modify_bg(Gtk::STATE_NORMAL,Gdk::Color.parse("black"))
file = ARGV[0] if ARGV[0]
file = File.read(@currentfile).chomp unless file
image = Gtk::Image.new file
ratio = [win.screen.width/image.pixbuf.width.to_f, win.screen.height.to_f/image.pixbuf.height].min
image.pixbuf = image.pixbuf.scale(image.pixbuf.width*ratio, image.pixbuf.height*ratio)
win.add(image)
win.signal_connect("key-press-event") do |w,e|
  case Gdk::Keyval.to_name(e.keyval)
  when "q"
    Gtk.main_quit
  end
end
win.signal_connect("destroy") { Gtk.main_quit }
win.show_all
Gtk.main
