#!/usr/bin/env ruby
require 'yaml'
require 'mini_exiftool'
require_relative "fim.rb"

ARGV.each do |file|
  thumbnail = file.sub(/#{@imagedir}/,@thumbdir).sub(/jpg/i,'png')
  exif = MiniExiftool.new file
  height = 100
  width = 16*height/9
  ratio = [width/exif.imagewidth.to_f, height/exif.imageheight.to_f].min
  width = (exif.imagewidth*ratio).round
  height = (exif.imageheight*ratio).round
  `/usr/bin/mkdir -p #{File.dirname(thumbnail)}`
  `gm convert "#{file}" -thumbnail #{width}x#{height} -strip "#{thumbnail}"`
end
