#!/usr/bin/env ruby
require 'rubygems'
require 'yaml'
require 'mini_exiftool'

tags = {}
tags["all"] = []
Dir["public/**/*{jpg,JPG,jpeg}"].each do |i|
  puts i
  keywords = MiniExiftool.new(i)['keywords'].to_a
  tags["all"] << i
  keywords.each do |tag|
    tags[tag] = [] if tags[tag].nil?
    tags[tag] << i
    puts tag
  end
  t = i.sub(/public/,"public/thumbs").sub(/jpg/i,'png')
  #unless File.exists?(t)
  puts t
  `mkdir -p #{File.dirname(t)}`
  `convert #{i} -thumbnail x100 -auto-orient -strip  #{t}`
  #end
end
File.open('tags.yaml', 'w+') { |out| YAML::dump(tags, out) }
